# Packfire Framework for PHP
#
# this file provides configuration for Travis Continuous Integration
# See Packfire on TravisCI at http://travis-ci.org/packfire/packfire-framework

language: php
php:
  - "5.3"
  - "5.3.3"
  - "5.4"
  - "5.5"
before_script:
  - composer install --prefer-source
script: phpunit -c phpunit.xml.dist
after_script:
  - "wget --quiet http://mauris.sg/bin/pdc.phar | php -- src"